# Generated by Django 5.2.4 on 2025-07-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('vuelo', 'pasajero'), name='unico_pasajero_por_vuelo'),
        ),
    ]
